#! /bin/sh

#Autostart
sxhkd &
$HOME/.config/polybar/launch.sh
picom --experimental-backend &

#Workspaces
bspc monitor -d I II III IV V 

#Other
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Custom
feh --bg-fill $HOME/Downloads/Downloaded-Pictures/saber.png

#Cursor
xsetroot -cursor_name left_ptr &
